#############################################################################
# Makefile for building: onlineServicesStandAlone
# Generated by qmake (2.01a) (Qt 4.6.3) on: Wed Jul 14 10:32:20 2010
# Project:  onlineServicesStandAlone.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile onlineServicesStandAlone.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include -I. -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = googlecontenthandler.cpp \
		googledocument.cpp \
		googledocumentlist.cpp \
		googledocumentservice.cpp \
		loginwindow.cpp \
		main.cpp \
		slideshare.cpp \
		slidesharelistdialog.cpp \
		slideshareuploaddialog.cpp \
		googlelistdialog.cpp \
		mimetypes.cpp \
		googleuploaddialog.cpp moc_googledocumentservice.cpp \
		moc_loginwindow.cpp \
		moc_slideshare.cpp \
		moc_slidesharelistdialog.cpp \
		moc_slideshareuploaddialog.cpp \
		moc_googlelistdialog.cpp \
		moc_googleuploaddialog.cpp
OBJECTS       = googlecontenthandler.o \
		googledocument.o \
		googledocumentlist.o \
		googledocumentservice.o \
		loginwindow.o \
		main.o \
		slideshare.o \
		slidesharelistdialog.o \
		slideshareuploaddialog.o \
		googlelistdialog.o \
		mimetypes.o \
		googleuploaddialog.o \
		moc_googledocumentservice.o \
		moc_loginwindow.o \
		moc_slideshare.o \
		moc_slidesharelistdialog.o \
		moc_slideshareuploaddialog.o \
		moc_googlelistdialog.o \
		moc_googleuploaddialog.o
DIST          = /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		onlineServicesStandAlone.pro
QMAKE_TARGET  = onlineServicesStandAlone
DESTDIR       = 
TARGET        = onlineServicesStandAlone

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_authenticationdialog.h ui_filelistdialog.h ui_uploaddialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: onlineServicesStandAlone.pro  /usr/share/qt/mkspecs/linux-g++-64/qmake.conf /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile onlineServicesStandAlone.pro
/usr/share/qt/mkspecs/common/g++.conf:
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/release.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile onlineServicesStandAlone.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/onlineServicesStandAlone1.0.0 || $(MKDIR) .tmp/onlineServicesStandAlone1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/onlineServicesStandAlone1.0.0/ && $(COPY_FILE) --parents googlecontenthandler.h googledocument.h googledocumentlist.h googledocumentservice.h loginwindow.h slideshare.h slidesharelistdialog.h slideshareuploaddialog.h slideshareDocument.h mimetypes.h googlelistdialog.h googleuploaddialog.h .tmp/onlineServicesStandAlone1.0.0/ && $(COPY_FILE) --parents googlecontenthandler.cpp googledocument.cpp googledocumentlist.cpp googledocumentservice.cpp loginwindow.cpp main.cpp slideshare.cpp slidesharelistdialog.cpp slideshareuploaddialog.cpp googlelistdialog.cpp mimetypes.cpp googleuploaddialog.cpp .tmp/onlineServicesStandAlone1.0.0/ && $(COPY_FILE) --parents authenticationdialog.ui filelistdialog.ui uploaddialog.ui .tmp/onlineServicesStandAlone1.0.0/ && (cd `dirname .tmp/onlineServicesStandAlone1.0.0` && $(TAR) onlineServicesStandAlone1.0.0.tar onlineServicesStandAlone1.0.0 && $(COMPRESS) onlineServicesStandAlone1.0.0.tar) && $(MOVE) `dirname .tmp/onlineServicesStandAlone1.0.0`/onlineServicesStandAlone1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/onlineServicesStandAlone1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_googledocumentservice.cpp moc_loginwindow.cpp moc_slideshare.cpp moc_slidesharelistdialog.cpp moc_slideshareuploaddialog.cpp moc_googlelistdialog.cpp moc_googleuploaddialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_googledocumentservice.cpp moc_loginwindow.cpp moc_slideshare.cpp moc_slidesharelistdialog.cpp moc_slideshareuploaddialog.cpp moc_googlelistdialog.cpp moc_googleuploaddialog.cpp
moc_googledocumentservice.cpp: googledocumentservice.h
	/usr/bin/moc $(DEFINES) $(INCPATH) googledocumentservice.h -o moc_googledocumentservice.cpp

moc_loginwindow.cpp: ui_authenticationdialog.h \
		loginwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) loginwindow.h -o moc_loginwindow.cpp

moc_slideshare.cpp: slideshare.h
	/usr/bin/moc $(DEFINES) $(INCPATH) slideshare.h -o moc_slideshare.cpp

moc_slidesharelistdialog.cpp: slideshare.h \
		slidesharelistdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) slidesharelistdialog.h -o moc_slidesharelistdialog.cpp

moc_slideshareuploaddialog.cpp: slideshareuploaddialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) slideshareuploaddialog.h -o moc_slideshareuploaddialog.cpp

moc_googlelistdialog.cpp: googledocumentservice.h \
		googlelistdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) googlelistdialog.h -o moc_googlelistdialog.cpp

moc_googleuploaddialog.cpp: googleuploaddialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) googleuploaddialog.h -o moc_googleuploaddialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_authenticationdialog.h ui_filelistdialog.h ui_uploaddialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_authenticationdialog.h ui_filelistdialog.h ui_uploaddialog.h
ui_authenticationdialog.h: authenticationdialog.ui
	/usr/bin/uic authenticationdialog.ui -o ui_authenticationdialog.h

ui_filelistdialog.h: filelistdialog.ui
	/usr/bin/uic filelistdialog.ui -o ui_filelistdialog.h

ui_uploaddialog.h: uploaddialog.ui
	/usr/bin/uic uploaddialog.ui -o ui_uploaddialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

googlecontenthandler.o: googlecontenthandler.cpp googledocumentlist.h \
		googledocument.h \
		googlecontenthandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o googlecontenthandler.o googlecontenthandler.cpp

googledocument.o: googledocument.cpp googledocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o googledocument.o googledocument.cpp

googledocumentlist.o: googledocumentlist.cpp googledocumentlist.h \
		googledocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o googledocumentlist.o googledocumentlist.cpp

googledocumentservice.o: googledocumentservice.cpp googledocumentservice.h \
		googledocumentlist.h \
		googledocument.h \
		googlecontenthandler.h \
		mimetypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o googledocumentservice.o googledocumentservice.cpp

loginwindow.o: loginwindow.cpp loginwindow.h \
		ui_authenticationdialog.h \
		googledocumentservice.h \
		googlelistdialog.h \
		slideshare.h \
		slidesharelistdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loginwindow.o loginwindow.cpp

main.o: main.cpp loginwindow.h \
		ui_authenticationdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

slideshare.o: slideshare.cpp slideshare.h \
		slideshareDocument.h \
		mimetypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o slideshare.o slideshare.cpp

slidesharelistdialog.o: slidesharelistdialog.cpp slidesharelistdialog.h \
		slideshare.h \
		ui_filelistdialog.h \
		slideshareuploaddialog.h \
		slideshareDocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o slidesharelistdialog.o slidesharelistdialog.cpp

slideshareuploaddialog.o: slideshareuploaddialog.cpp slideshareuploaddialog.h \
		ui_uploaddialog.h \
		slideshare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o slideshareuploaddialog.o slideshareuploaddialog.cpp

googlelistdialog.o: googlelistdialog.cpp googlelistdialog.h \
		googledocumentservice.h \
		ui_filelistdialog.h \
		googledocument.h \
		googleuploaddialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o googlelistdialog.o googlelistdialog.cpp

mimetypes.o: mimetypes.cpp mimetypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mimetypes.o mimetypes.cpp

googleuploaddialog.o: googleuploaddialog.cpp googleuploaddialog.h \
		ui_uploaddialog.h \
		googledocumentservice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o googleuploaddialog.o googleuploaddialog.cpp

moc_googledocumentservice.o: moc_googledocumentservice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_googledocumentservice.o moc_googledocumentservice.cpp

moc_loginwindow.o: moc_loginwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loginwindow.o moc_loginwindow.cpp

moc_slideshare.o: moc_slideshare.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_slideshare.o moc_slideshare.cpp

moc_slidesharelistdialog.o: moc_slidesharelistdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_slidesharelistdialog.o moc_slidesharelistdialog.cpp

moc_slideshareuploaddialog.o: moc_slideshareuploaddialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_slideshareuploaddialog.o moc_slideshareuploaddialog.cpp

moc_googlelistdialog.o: moc_googlelistdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_googlelistdialog.o moc_googlelistdialog.cpp

moc_googleuploaddialog.o: moc_googleuploaddialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_googleuploaddialog.o moc_googleuploaddialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

